/********************************************************************************
** Form generated from reading UI file 'lightedit.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LIGHTEDIT_H
#define UI_LIGHTEDIT_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QLabel>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_LightEdit
{
public:
    QCheckBox *checkBoxX1;
    QCheckBox *checkBoxX2;
    QCheckBox *checkBoxX3;
    QCheckBox *checkBoxX4;
    QCheckBox *checkBoxY1;
    QCheckBox *checkBoxY2;
    QCheckBox *checkBoxY3;
    QCheckBox *checkBoxY4;
    QLabel *labelY1;
    QLabel *labelY2;
    QLabel *labelY3;
    QLabel *labelY4;
    QLabel *labelY5;
    QLabel *labelY6;
    QLabel *labelY7;
    QLabel *labelY8;
    QLabel *labelY9;
    QLabel *labelY10;
    QLabel *labelY11;
    QLabel *labelY12;
    QLabel *labelY13;
    QLabel *labelY14;
    QLabel *labelY15;
    QLabel *labelY16;
    QLabel *labelY17;
    QLabel *labelY18;
    QLabel *labelY19;
    QLabel *labelY20;
    QLabel *labelY21;
    QLabel *labelY22;
    QLabel *labelY23;
    QLabel *labelY24;
    QLabel *labelX1;
    QLabel *labelX2;
    QLabel *labelX3;
    QLabel *labelX4;
    QLabel *labelX5;
    QLabel *labelX6;
    QLabel *labelX7;
    QLabel *labelX8;
    QLabel *labelX9;
    QLabel *labelX10;
    QLabel *labelX11;
    QLabel *labelX12;
    QLabel *labelX23;
    QLabel *labelX15;
    QLabel *labelX16;
    QLabel *labelX21;
    QLabel *labelX24;
    QLabel *labelX22;
    QLabel *labelX20;
    QLabel *labelX17;
    QLabel *labelX14;
    QLabel *labelX18;
    QLabel *labelX13;
    QLabel *labelX19;
    QCheckBox *checkBoxY8;
    QCheckBox *checkBoxY7;
    QCheckBox *checkBoxY5;
    QCheckBox *checkBoxY6;
    QCheckBox *checkBoxY16;
    QCheckBox *checkBoxY11;
    QCheckBox *checkBoxY9;
    QCheckBox *checkBoxY12;
    QCheckBox *checkBoxY10;
    QCheckBox *checkBoxY15;
    QCheckBox *checkBoxY14;
    QCheckBox *checkBoxY13;
    QCheckBox *checkBoxY17;
    QCheckBox *checkBoxY18;
    QCheckBox *checkBoxY19;
    QCheckBox *checkBoxY23;
    QCheckBox *checkBoxY22;
    QCheckBox *checkBoxY20;
    QCheckBox *checkBoxY24;
    QCheckBox *checkBoxY21;
    QCheckBox *checkBoxX8;
    QCheckBox *checkBoxX7;
    QCheckBox *checkBoxX6;
    QCheckBox *checkBoxX5;
    QCheckBox *checkBoxX16;
    QCheckBox *checkBoxX11;
    QCheckBox *checkBoxX12;
    QCheckBox *checkBoxX14;
    QCheckBox *checkBoxX10;
    QCheckBox *checkBoxX9;
    QCheckBox *checkBoxX15;
    QCheckBox *checkBoxX13;
    QCheckBox *checkBoxX19;
    QCheckBox *checkBoxX20;
    QCheckBox *checkBoxX22;
    QCheckBox *checkBoxX18;
    QCheckBox *checkBoxX17;
    QCheckBox *checkBoxX23;
    QCheckBox *checkBoxX24;
    QCheckBox *checkBoxX21;
    QLabel *label;
    QLabel *label_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_5;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLabel *label_19;
    QLabel *label_20;
    QLabel *label_21;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QLabel *label_25;
    QLabel *label_26;
    QLabel *label_27;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLabel *label_32;
    QLabel *label_33;
    QLabel *label_34;
    QLabel *label_35;
    QLabel *label_36;
    QLabel *label_37;
    QLabel *label_38;
    QLabel *label_39;
    QLabel *label_40;
    QLabel *label_41;
    QLabel *label_42;
    QLabel *label_43;
    QLabel *label_44;
    QLabel *label_45;
    QLabel *label_46;
    QLabel *label_47;
    QLabel *label_48;
    QPushButton *pushButton;

    void setupUi(QDialog *LightEdit)
    {
        if (LightEdit->objectName().isEmpty())
            LightEdit->setObjectName(QString::fromUtf8("LightEdit"));
        LightEdit->resize(1078, 691);
        LightEdit->setStyleSheet(QString::fromUtf8("QDialog {\n"
"    border-image: url(:/icon/LE.png) 0 0 0 0 stretch stretch;\n"
"}"));
        checkBoxX1 = new QCheckBox(LightEdit);
        checkBoxX1->setObjectName(QString::fromUtf8("checkBoxX1"));
        checkBoxX1->setGeometry(QRect(70, 42, 16, 16));
        checkBoxX2 = new QCheckBox(LightEdit);
        checkBoxX2->setObjectName(QString::fromUtf8("checkBoxX2"));
        checkBoxX2->setGeometry(QRect(94, 42, 16, 16));
        checkBoxX3 = new QCheckBox(LightEdit);
        checkBoxX3->setObjectName(QString::fromUtf8("checkBoxX3"));
        checkBoxX3->setGeometry(QRect(117, 42, 16, 16));
        checkBoxX4 = new QCheckBox(LightEdit);
        checkBoxX4->setObjectName(QString::fromUtf8("checkBoxX4"));
        checkBoxX4->setGeometry(QRect(139, 42, 16, 16));
        checkBoxY1 = new QCheckBox(LightEdit);
        checkBoxY1->setObjectName(QString::fromUtf8("checkBoxY1"));
        checkBoxY1->setGeometry(QRect(24, 78, 16, 16));
        checkBoxY2 = new QCheckBox(LightEdit);
        checkBoxY2->setObjectName(QString::fromUtf8("checkBoxY2"));
        checkBoxY2->setGeometry(QRect(24, 101, 16, 16));
        checkBoxY3 = new QCheckBox(LightEdit);
        checkBoxY3->setObjectName(QString::fromUtf8("checkBoxY3"));
        checkBoxY3->setGeometry(QRect(24, 124, 16, 16));
        checkBoxY4 = new QCheckBox(LightEdit);
        checkBoxY4->setObjectName(QString::fromUtf8("checkBoxY4"));
        checkBoxY4->setGeometry(QRect(24, 147, 16, 16));
        labelY1 = new QLabel(LightEdit);
        labelY1->setObjectName(QString::fromUtf8("labelY1"));
        labelY1->setGeometry(QRect(70, 80, 544, 16));
        labelY1->setMinimumSize(QSize(520, 15));
        labelY2 = new QLabel(LightEdit);
        labelY2->setObjectName(QString::fromUtf8("labelY2"));
        labelY2->setGeometry(QRect(70, 103, 544, 16));
        labelY2->setMinimumSize(QSize(520, 15));
        labelY3 = new QLabel(LightEdit);
        labelY3->setObjectName(QString::fromUtf8("labelY3"));
        labelY3->setGeometry(QRect(70, 126, 544, 16));
        labelY3->setMinimumSize(QSize(520, 15));
        labelY4 = new QLabel(LightEdit);
        labelY4->setObjectName(QString::fromUtf8("labelY4"));
        labelY4->setGeometry(QRect(70, 149, 544, 16));
        labelY4->setMinimumSize(QSize(520, 15));
        labelY5 = new QLabel(LightEdit);
        labelY5->setObjectName(QString::fromUtf8("labelY5"));
        labelY5->setGeometry(QRect(70, 172, 544, 16));
        labelY5->setMinimumSize(QSize(520, 15));
        labelY6 = new QLabel(LightEdit);
        labelY6->setObjectName(QString::fromUtf8("labelY6"));
        labelY6->setGeometry(QRect(70, 196, 544, 16));
        labelY6->setMinimumSize(QSize(520, 15));
        labelY7 = new QLabel(LightEdit);
        labelY7->setObjectName(QString::fromUtf8("labelY7"));
        labelY7->setGeometry(QRect(70, 219, 544, 16));
        labelY7->setMinimumSize(QSize(520, 15));
        labelY8 = new QLabel(LightEdit);
        labelY8->setObjectName(QString::fromUtf8("labelY8"));
        labelY8->setGeometry(QRect(70, 242, 544, 16));
        labelY8->setMinimumSize(QSize(520, 15));
        labelY9 = new QLabel(LightEdit);
        labelY9->setObjectName(QString::fromUtf8("labelY9"));
        labelY9->setGeometry(QRect(70, 265, 544, 16));
        labelY9->setMinimumSize(QSize(520, 15));
        labelY10 = new QLabel(LightEdit);
        labelY10->setObjectName(QString::fromUtf8("labelY10"));
        labelY10->setGeometry(QRect(70, 288, 544, 16));
        labelY10->setMinimumSize(QSize(520, 15));
        labelY11 = new QLabel(LightEdit);
        labelY11->setObjectName(QString::fromUtf8("labelY11"));
        labelY11->setGeometry(QRect(70, 311, 544, 16));
        labelY11->setMinimumSize(QSize(520, 15));
        labelY12 = new QLabel(LightEdit);
        labelY12->setObjectName(QString::fromUtf8("labelY12"));
        labelY12->setGeometry(QRect(70, 334, 544, 16));
        labelY12->setMinimumSize(QSize(520, 15));
        labelY13 = new QLabel(LightEdit);
        labelY13->setObjectName(QString::fromUtf8("labelY13"));
        labelY13->setGeometry(QRect(70, 357, 544, 16));
        labelY13->setMinimumSize(QSize(520, 15));
        labelY14 = new QLabel(LightEdit);
        labelY14->setObjectName(QString::fromUtf8("labelY14"));
        labelY14->setGeometry(QRect(70, 381, 544, 16));
        labelY14->setMinimumSize(QSize(520, 15));
        labelY15 = new QLabel(LightEdit);
        labelY15->setObjectName(QString::fromUtf8("labelY15"));
        labelY15->setGeometry(QRect(70, 404, 544, 16));
        labelY15->setMinimumSize(QSize(520, 15));
        labelY16 = new QLabel(LightEdit);
        labelY16->setObjectName(QString::fromUtf8("labelY16"));
        labelY16->setGeometry(QRect(70, 427, 544, 16));
        labelY16->setMinimumSize(QSize(520, 15));
        labelY17 = new QLabel(LightEdit);
        labelY17->setObjectName(QString::fromUtf8("labelY17"));
        labelY17->setGeometry(QRect(70, 450, 544, 16));
        labelY17->setMinimumSize(QSize(520, 15));
        labelY18 = new QLabel(LightEdit);
        labelY18->setObjectName(QString::fromUtf8("labelY18"));
        labelY18->setGeometry(QRect(70, 473, 544, 16));
        labelY18->setMinimumSize(QSize(520, 15));
        labelY19 = new QLabel(LightEdit);
        labelY19->setObjectName(QString::fromUtf8("labelY19"));
        labelY19->setGeometry(QRect(70, 496, 544, 16));
        labelY19->setMinimumSize(QSize(520, 15));
        labelY20 = new QLabel(LightEdit);
        labelY20->setObjectName(QString::fromUtf8("labelY20"));
        labelY20->setGeometry(QRect(70, 519, 544, 16));
        labelY20->setMinimumSize(QSize(520, 15));
        labelY21 = new QLabel(LightEdit);
        labelY21->setObjectName(QString::fromUtf8("labelY21"));
        labelY21->setGeometry(QRect(70, 542, 544, 16));
        labelY21->setMinimumSize(QSize(520, 15));
        labelY22 = new QLabel(LightEdit);
        labelY22->setObjectName(QString::fromUtf8("labelY22"));
        labelY22->setGeometry(QRect(70, 566, 544, 16));
        labelY22->setMinimumSize(QSize(520, 15));
        labelY23 = new QLabel(LightEdit);
        labelY23->setObjectName(QString::fromUtf8("labelY23"));
        labelY23->setGeometry(QRect(70, 589, 544, 16));
        labelY23->setMinimumSize(QSize(520, 15));
        labelY24 = new QLabel(LightEdit);
        labelY24->setObjectName(QString::fromUtf8("labelY24"));
        labelY24->setGeometry(QRect(70, 612, 544, 16));
        labelY24->setMinimumSize(QSize(520, 15));
        labelX1 = new QLabel(LightEdit);
        labelX1->setObjectName(QString::fromUtf8("labelX1"));
        labelX1->setGeometry(QRect(70, 80, 15, 547));
        labelX2 = new QLabel(LightEdit);
        labelX2->setObjectName(QString::fromUtf8("labelX2"));
        labelX2->setGeometry(QRect(93, 80, 15, 547));
        labelX3 = new QLabel(LightEdit);
        labelX3->setObjectName(QString::fromUtf8("labelX3"));
        labelX3->setGeometry(QRect(116, 80, 15, 547));
        labelX4 = new QLabel(LightEdit);
        labelX4->setObjectName(QString::fromUtf8("labelX4"));
        labelX4->setGeometry(QRect(139, 80, 15, 547));
        labelX5 = new QLabel(LightEdit);
        labelX5->setObjectName(QString::fromUtf8("labelX5"));
        labelX5->setGeometry(QRect(162, 80, 15, 547));
        labelX6 = new QLabel(LightEdit);
        labelX6->setObjectName(QString::fromUtf8("labelX6"));
        labelX6->setGeometry(QRect(185, 80, 15, 547));
        labelX7 = new QLabel(LightEdit);
        labelX7->setObjectName(QString::fromUtf8("labelX7"));
        labelX7->setGeometry(QRect(208, 80, 15, 547));
        labelX8 = new QLabel(LightEdit);
        labelX8->setObjectName(QString::fromUtf8("labelX8"));
        labelX8->setGeometry(QRect(231, 80, 15, 547));
        labelX9 = new QLabel(LightEdit);
        labelX9->setObjectName(QString::fromUtf8("labelX9"));
        labelX9->setGeometry(QRect(254, 80, 15, 547));
        labelX10 = new QLabel(LightEdit);
        labelX10->setObjectName(QString::fromUtf8("labelX10"));
        labelX10->setGeometry(QRect(277, 80, 15, 547));
        labelX11 = new QLabel(LightEdit);
        labelX11->setObjectName(QString::fromUtf8("labelX11"));
        labelX11->setGeometry(QRect(300, 80, 15, 547));
        labelX12 = new QLabel(LightEdit);
        labelX12->setObjectName(QString::fromUtf8("labelX12"));
        labelX12->setGeometry(QRect(323, 80, 15, 547));
        labelX23 = new QLabel(LightEdit);
        labelX23->setObjectName(QString::fromUtf8("labelX23"));
        labelX23->setGeometry(QRect(576, 80, 15, 547));
        labelX15 = new QLabel(LightEdit);
        labelX15->setObjectName(QString::fromUtf8("labelX15"));
        labelX15->setGeometry(QRect(392, 80, 15, 547));
        labelX16 = new QLabel(LightEdit);
        labelX16->setObjectName(QString::fromUtf8("labelX16"));
        labelX16->setGeometry(QRect(415, 80, 15, 547));
        labelX21 = new QLabel(LightEdit);
        labelX21->setObjectName(QString::fromUtf8("labelX21"));
        labelX21->setGeometry(QRect(530, 80, 15, 547));
        labelX24 = new QLabel(LightEdit);
        labelX24->setObjectName(QString::fromUtf8("labelX24"));
        labelX24->setGeometry(QRect(599, 80, 15, 547));
        labelX22 = new QLabel(LightEdit);
        labelX22->setObjectName(QString::fromUtf8("labelX22"));
        labelX22->setGeometry(QRect(553, 80, 15, 547));
        labelX20 = new QLabel(LightEdit);
        labelX20->setObjectName(QString::fromUtf8("labelX20"));
        labelX20->setGeometry(QRect(507, 80, 15, 547));
        labelX17 = new QLabel(LightEdit);
        labelX17->setObjectName(QString::fromUtf8("labelX17"));
        labelX17->setGeometry(QRect(438, 80, 15, 547));
        labelX14 = new QLabel(LightEdit);
        labelX14->setObjectName(QString::fromUtf8("labelX14"));
        labelX14->setGeometry(QRect(369, 80, 15, 547));
        labelX18 = new QLabel(LightEdit);
        labelX18->setObjectName(QString::fromUtf8("labelX18"));
        labelX18->setGeometry(QRect(461, 80, 15, 547));
        labelX13 = new QLabel(LightEdit);
        labelX13->setObjectName(QString::fromUtf8("labelX13"));
        labelX13->setGeometry(QRect(346, 80, 15, 547));
        labelX19 = new QLabel(LightEdit);
        labelX19->setObjectName(QString::fromUtf8("labelX19"));
        labelX19->setGeometry(QRect(484, 80, 15, 547));
        checkBoxY8 = new QCheckBox(LightEdit);
        checkBoxY8->setObjectName(QString::fromUtf8("checkBoxY8"));
        checkBoxY8->setGeometry(QRect(24, 240, 16, 16));
        checkBoxY7 = new QCheckBox(LightEdit);
        checkBoxY7->setObjectName(QString::fromUtf8("checkBoxY7"));
        checkBoxY7->setGeometry(QRect(24, 217, 16, 16));
        checkBoxY5 = new QCheckBox(LightEdit);
        checkBoxY5->setObjectName(QString::fromUtf8("checkBoxY5"));
        checkBoxY5->setGeometry(QRect(24, 170, 16, 16));
        checkBoxY6 = new QCheckBox(LightEdit);
        checkBoxY6->setObjectName(QString::fromUtf8("checkBoxY6"));
        checkBoxY6->setGeometry(QRect(24, 194, 16, 16));
        checkBoxY16 = new QCheckBox(LightEdit);
        checkBoxY16->setObjectName(QString::fromUtf8("checkBoxY16"));
        checkBoxY16->setGeometry(QRect(24, 425, 16, 16));
        checkBoxY11 = new QCheckBox(LightEdit);
        checkBoxY11->setObjectName(QString::fromUtf8("checkBoxY11"));
        checkBoxY11->setGeometry(QRect(24, 309, 16, 16));
        checkBoxY9 = new QCheckBox(LightEdit);
        checkBoxY9->setObjectName(QString::fromUtf8("checkBoxY9"));
        checkBoxY9->setGeometry(QRect(24, 263, 16, 16));
        checkBoxY12 = new QCheckBox(LightEdit);
        checkBoxY12->setObjectName(QString::fromUtf8("checkBoxY12"));
        checkBoxY12->setGeometry(QRect(24, 332, 16, 16));
        checkBoxY10 = new QCheckBox(LightEdit);
        checkBoxY10->setObjectName(QString::fromUtf8("checkBoxY10"));
        checkBoxY10->setGeometry(QRect(24, 286, 16, 16));
        checkBoxY15 = new QCheckBox(LightEdit);
        checkBoxY15->setObjectName(QString::fromUtf8("checkBoxY15"));
        checkBoxY15->setGeometry(QRect(24, 402, 16, 16));
        checkBoxY14 = new QCheckBox(LightEdit);
        checkBoxY14->setObjectName(QString::fromUtf8("checkBoxY14"));
        checkBoxY14->setGeometry(QRect(24, 379, 16, 16));
        checkBoxY13 = new QCheckBox(LightEdit);
        checkBoxY13->setObjectName(QString::fromUtf8("checkBoxY13"));
        checkBoxY13->setGeometry(QRect(24, 355, 16, 16));
        checkBoxY17 = new QCheckBox(LightEdit);
        checkBoxY17->setObjectName(QString::fromUtf8("checkBoxY17"));
        checkBoxY17->setGeometry(QRect(24, 448, 16, 16));
        checkBoxY18 = new QCheckBox(LightEdit);
        checkBoxY18->setObjectName(QString::fromUtf8("checkBoxY18"));
        checkBoxY18->setGeometry(QRect(24, 471, 16, 16));
        checkBoxY19 = new QCheckBox(LightEdit);
        checkBoxY19->setObjectName(QString::fromUtf8("checkBoxY19"));
        checkBoxY19->setGeometry(QRect(24, 494, 16, 16));
        checkBoxY23 = new QCheckBox(LightEdit);
        checkBoxY23->setObjectName(QString::fromUtf8("checkBoxY23"));
        checkBoxY23->setGeometry(QRect(24, 587, 16, 16));
        checkBoxY22 = new QCheckBox(LightEdit);
        checkBoxY22->setObjectName(QString::fromUtf8("checkBoxY22"));
        checkBoxY22->setGeometry(QRect(24, 564, 16, 16));
        checkBoxY20 = new QCheckBox(LightEdit);
        checkBoxY20->setObjectName(QString::fromUtf8("checkBoxY20"));
        checkBoxY20->setGeometry(QRect(24, 517, 16, 16));
        checkBoxY24 = new QCheckBox(LightEdit);
        checkBoxY24->setObjectName(QString::fromUtf8("checkBoxY24"));
        checkBoxY24->setGeometry(QRect(24, 610, 16, 16));
        checkBoxY21 = new QCheckBox(LightEdit);
        checkBoxY21->setObjectName(QString::fromUtf8("checkBoxY21"));
        checkBoxY21->setGeometry(QRect(24, 540, 16, 16));
        checkBoxX8 = new QCheckBox(LightEdit);
        checkBoxX8->setObjectName(QString::fromUtf8("checkBoxX8"));
        checkBoxX8->setGeometry(QRect(232, 42, 16, 16));
        checkBoxX7 = new QCheckBox(LightEdit);
        checkBoxX7->setObjectName(QString::fromUtf8("checkBoxX7"));
        checkBoxX7->setGeometry(QRect(209, 42, 16, 16));
        checkBoxX6 = new QCheckBox(LightEdit);
        checkBoxX6->setObjectName(QString::fromUtf8("checkBoxX6"));
        checkBoxX6->setGeometry(QRect(186, 42, 16, 16));
        checkBoxX5 = new QCheckBox(LightEdit);
        checkBoxX5->setObjectName(QString::fromUtf8("checkBoxX5"));
        checkBoxX5->setGeometry(QRect(163, 42, 16, 16));
        checkBoxX16 = new QCheckBox(LightEdit);
        checkBoxX16->setObjectName(QString::fromUtf8("checkBoxX16"));
        checkBoxX16->setGeometry(QRect(416, 42, 16, 16));
        checkBoxX11 = new QCheckBox(LightEdit);
        checkBoxX11->setObjectName(QString::fromUtf8("checkBoxX11"));
        checkBoxX11->setGeometry(QRect(301, 42, 16, 16));
        checkBoxX12 = new QCheckBox(LightEdit);
        checkBoxX12->setObjectName(QString::fromUtf8("checkBoxX12"));
        checkBoxX12->setGeometry(QRect(324, 42, 16, 16));
        checkBoxX14 = new QCheckBox(LightEdit);
        checkBoxX14->setObjectName(QString::fromUtf8("checkBoxX14"));
        checkBoxX14->setGeometry(QRect(370, 42, 16, 16));
        checkBoxX10 = new QCheckBox(LightEdit);
        checkBoxX10->setObjectName(QString::fromUtf8("checkBoxX10"));
        checkBoxX10->setGeometry(QRect(278, 42, 16, 16));
        checkBoxX9 = new QCheckBox(LightEdit);
        checkBoxX9->setObjectName(QString::fromUtf8("checkBoxX9"));
        checkBoxX9->setGeometry(QRect(255, 42, 16, 16));
        checkBoxX15 = new QCheckBox(LightEdit);
        checkBoxX15->setObjectName(QString::fromUtf8("checkBoxX15"));
        checkBoxX15->setGeometry(QRect(393, 42, 16, 16));
        checkBoxX13 = new QCheckBox(LightEdit);
        checkBoxX13->setObjectName(QString::fromUtf8("checkBoxX13"));
        checkBoxX13->setGeometry(QRect(347, 42, 16, 16));
        checkBoxX19 = new QCheckBox(LightEdit);
        checkBoxX19->setObjectName(QString::fromUtf8("checkBoxX19"));
        checkBoxX19->setGeometry(QRect(485, 42, 16, 16));
        checkBoxX20 = new QCheckBox(LightEdit);
        checkBoxX20->setObjectName(QString::fromUtf8("checkBoxX20"));
        checkBoxX20->setGeometry(QRect(508, 42, 16, 16));
        checkBoxX22 = new QCheckBox(LightEdit);
        checkBoxX22->setObjectName(QString::fromUtf8("checkBoxX22"));
        checkBoxX22->setGeometry(QRect(554, 42, 16, 16));
        checkBoxX18 = new QCheckBox(LightEdit);
        checkBoxX18->setObjectName(QString::fromUtf8("checkBoxX18"));
        checkBoxX18->setGeometry(QRect(462, 42, 16, 16));
        checkBoxX17 = new QCheckBox(LightEdit);
        checkBoxX17->setObjectName(QString::fromUtf8("checkBoxX17"));
        checkBoxX17->setGeometry(QRect(439, 42, 16, 16));
        checkBoxX23 = new QCheckBox(LightEdit);
        checkBoxX23->setObjectName(QString::fromUtf8("checkBoxX23"));
        checkBoxX23->setGeometry(QRect(577, 42, 16, 16));
        checkBoxX24 = new QCheckBox(LightEdit);
        checkBoxX24->setObjectName(QString::fromUtf8("checkBoxX24"));
        checkBoxX24->setGeometry(QRect(600, 42, 16, 16));
        checkBoxX21 = new QCheckBox(LightEdit);
        checkBoxX21->setObjectName(QString::fromUtf8("checkBoxX21"));
        checkBoxX21->setGeometry(QRect(531, 42, 16, 16));
        label = new QLabel(LightEdit);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(53, 78, 21, 20));
        label_2 = new QLabel(LightEdit);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(53, 101, 21, 20));
        label_3 = new QLabel(LightEdit);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(53, 124, 21, 20));
        label_4 = new QLabel(LightEdit);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(53, 147, 21, 20));
        label_5 = new QLabel(LightEdit);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(53, 170, 21, 20));
        label_6 = new QLabel(LightEdit);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(53, 194, 21, 20));
        label_7 = new QLabel(LightEdit);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(72, 60, 21, 20));
        label_8 = new QLabel(LightEdit);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(95, 60, 21, 20));
        label_9 = new QLabel(LightEdit);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(118, 60, 21, 20));
        label_10 = new QLabel(LightEdit);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(141, 60, 21, 20));
        label_11 = new QLabel(LightEdit);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(165, 60, 21, 20));
        label_12 = new QLabel(LightEdit);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(188, 60, 21, 20));
        label_13 = new QLabel(LightEdit);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(211, 60, 21, 20));
        label_14 = new QLabel(LightEdit);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(234, 60, 21, 20));
        label_15 = new QLabel(LightEdit);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(257, 60, 21, 20));
        label_16 = new QLabel(LightEdit);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(278, 60, 21, 20));
        label_17 = new QLabel(LightEdit);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(301, 60, 21, 20));
        label_18 = new QLabel(LightEdit);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(324, 60, 21, 20));
        label_19 = new QLabel(LightEdit);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(347, 60, 21, 20));
        label_20 = new QLabel(LightEdit);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(370, 60, 21, 20));
        label_21 = new QLabel(LightEdit);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(393, 60, 21, 20));
        label_22 = new QLabel(LightEdit);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(416, 60, 21, 20));
        label_23 = new QLabel(LightEdit);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(439, 60, 21, 20));
        label_24 = new QLabel(LightEdit);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(462, 60, 21, 20));
        label_25 = new QLabel(LightEdit);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(485, 60, 21, 20));
        label_26 = new QLabel(LightEdit);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(508, 60, 21, 20));
        label_27 = new QLabel(LightEdit);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(531, 60, 21, 20));
        label_28 = new QLabel(LightEdit);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(554, 60, 21, 20));
        label_29 = new QLabel(LightEdit);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(577, 60, 21, 20));
        label_30 = new QLabel(LightEdit);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(600, 60, 21, 20));
        label_31 = new QLabel(LightEdit);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(53, 217, 21, 20));
        label_32 = new QLabel(LightEdit);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(53, 240, 21, 20));
        label_33 = new QLabel(LightEdit);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(53, 263, 21, 20));
        label_34 = new QLabel(LightEdit);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(50, 286, 21, 20));
        label_35 = new QLabel(LightEdit);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(50, 309, 21, 20));
        label_36 = new QLabel(LightEdit);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(50, 332, 21, 20));
        label_37 = new QLabel(LightEdit);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(50, 355, 21, 20));
        label_38 = new QLabel(LightEdit);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(50, 379, 21, 20));
        label_39 = new QLabel(LightEdit);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(50, 402, 21, 20));
        label_40 = new QLabel(LightEdit);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(50, 425, 21, 20));
        label_41 = new QLabel(LightEdit);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(50, 448, 21, 20));
        label_42 = new QLabel(LightEdit);
        label_42->setObjectName(QString::fromUtf8("label_42"));
        label_42->setGeometry(QRect(50, 471, 21, 20));
        label_43 = new QLabel(LightEdit);
        label_43->setObjectName(QString::fromUtf8("label_43"));
        label_43->setGeometry(QRect(50, 494, 21, 20));
        label_44 = new QLabel(LightEdit);
        label_44->setObjectName(QString::fromUtf8("label_44"));
        label_44->setGeometry(QRect(50, 517, 21, 20));
        label_45 = new QLabel(LightEdit);
        label_45->setObjectName(QString::fromUtf8("label_45"));
        label_45->setGeometry(QRect(50, 540, 21, 20));
        label_46 = new QLabel(LightEdit);
        label_46->setObjectName(QString::fromUtf8("label_46"));
        label_46->setGeometry(QRect(50, 564, 21, 20));
        label_47 = new QLabel(LightEdit);
        label_47->setObjectName(QString::fromUtf8("label_47"));
        label_47->setGeometry(QRect(50, 587, 21, 20));
        label_48 = new QLabel(LightEdit);
        label_48->setObjectName(QString::fromUtf8("label_48"));
        label_48->setGeometry(QRect(50, 610, 21, 20));
        pushButton = new QPushButton(LightEdit);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(750, 613, 81, 21));

        retranslateUi(LightEdit);

        QMetaObject::connectSlotsByName(LightEdit);
    } // setupUi

    void retranslateUi(QDialog *LightEdit)
    {
        LightEdit->setWindowTitle(QApplication::translate("LightEdit", "Dialog", nullptr));
        checkBoxX1->setText(QString());
        checkBoxX2->setText(QString());
        checkBoxX3->setText(QString());
        checkBoxX4->setText(QString());
        checkBoxY1->setText(QString());
        checkBoxY2->setText(QString());
        checkBoxY3->setText(QString());
        checkBoxY4->setText(QString());
        labelY1->setText(QString());
        labelY2->setText(QString());
        labelY3->setText(QString());
        labelY4->setText(QString());
        labelY5->setText(QString());
        labelY6->setText(QString());
        labelY7->setText(QString());
        labelY8->setText(QString());
        labelY9->setText(QString());
        labelY10->setText(QString());
        labelY11->setText(QString());
        labelY12->setText(QString());
        labelY13->setText(QString());
        labelY14->setText(QString());
        labelY15->setText(QString());
        labelY16->setText(QString());
        labelY17->setText(QString());
        labelY18->setText(QString());
        labelY19->setText(QString());
        labelY20->setText(QString());
        labelY21->setText(QString());
        labelY22->setText(QString());
        labelY23->setText(QString());
        labelY24->setText(QString());
        labelX1->setText(QString());
        labelX2->setText(QString());
        labelX3->setText(QString());
        labelX4->setText(QString());
        labelX5->setText(QString());
        labelX6->setText(QString());
        labelX7->setText(QString());
        labelX8->setText(QString());
        labelX9->setText(QString());
        labelX10->setText(QString());
        labelX11->setText(QString());
        labelX12->setText(QString());
        labelX23->setText(QString());
        labelX15->setText(QString());
        labelX16->setText(QString());
        labelX21->setText(QString());
        labelX24->setText(QString());
        labelX22->setText(QString());
        labelX20->setText(QString());
        labelX17->setText(QString());
        labelX14->setText(QString());
        labelX18->setText(QString());
        labelX13->setText(QString());
        labelX19->setText(QString());
        checkBoxY8->setText(QString());
        checkBoxY7->setText(QString());
        checkBoxY5->setText(QString());
        checkBoxY6->setText(QString());
        checkBoxY16->setText(QString());
        checkBoxY11->setText(QString());
        checkBoxY9->setText(QString());
        checkBoxY12->setText(QString());
        checkBoxY10->setText(QString());
        checkBoxY15->setText(QString());
        checkBoxY14->setText(QString());
        checkBoxY13->setText(QString());
        checkBoxY17->setText(QString());
        checkBoxY18->setText(QString());
        checkBoxY19->setText(QString());
        checkBoxY23->setText(QString());
        checkBoxY22->setText(QString());
        checkBoxY20->setText(QString());
        checkBoxY24->setText(QString());
        checkBoxY21->setText(QString());
        checkBoxX8->setText(QString());
        checkBoxX7->setText(QString());
        checkBoxX6->setText(QString());
        checkBoxX5->setText(QString());
        checkBoxX16->setText(QString());
        checkBoxX11->setText(QString());
        checkBoxX12->setText(QString());
        checkBoxX14->setText(QString());
        checkBoxX10->setText(QString());
        checkBoxX9->setText(QString());
        checkBoxX15->setText(QString());
        checkBoxX13->setText(QString());
        checkBoxX19->setText(QString());
        checkBoxX20->setText(QString());
        checkBoxX22->setText(QString());
        checkBoxX18->setText(QString());
        checkBoxX17->setText(QString());
        checkBoxX23->setText(QString());
        checkBoxX24->setText(QString());
        checkBoxX21->setText(QString());
        label->setText(QApplication::translate("LightEdit", "1", nullptr));
        label_2->setText(QApplication::translate("LightEdit", "2", nullptr));
        label_3->setText(QApplication::translate("LightEdit", "3", nullptr));
        label_4->setText(QApplication::translate("LightEdit", "4", nullptr));
        label_5->setText(QApplication::translate("LightEdit", "5", nullptr));
        label_6->setText(QApplication::translate("LightEdit", "6", nullptr));
        label_7->setText(QApplication::translate("LightEdit", "1", nullptr));
        label_8->setText(QApplication::translate("LightEdit", "2", nullptr));
        label_9->setText(QApplication::translate("LightEdit", "3", nullptr));
        label_10->setText(QApplication::translate("LightEdit", "4", nullptr));
        label_11->setText(QApplication::translate("LightEdit", "5", nullptr));
        label_12->setText(QApplication::translate("LightEdit", "6", nullptr));
        label_13->setText(QApplication::translate("LightEdit", "7", nullptr));
        label_14->setText(QApplication::translate("LightEdit", "8", nullptr));
        label_15->setText(QApplication::translate("LightEdit", "9", nullptr));
        label_16->setText(QApplication::translate("LightEdit", "10", nullptr));
        label_17->setText(QApplication::translate("LightEdit", "11", nullptr));
        label_18->setText(QApplication::translate("LightEdit", "12", nullptr));
        label_19->setText(QApplication::translate("LightEdit", "13", nullptr));
        label_20->setText(QApplication::translate("LightEdit", "14", nullptr));
        label_21->setText(QApplication::translate("LightEdit", "15", nullptr));
        label_22->setText(QApplication::translate("LightEdit", "16", nullptr));
        label_23->setText(QApplication::translate("LightEdit", "17", nullptr));
        label_24->setText(QApplication::translate("LightEdit", "18", nullptr));
        label_25->setText(QApplication::translate("LightEdit", "19", nullptr));
        label_26->setText(QApplication::translate("LightEdit", "20", nullptr));
        label_27->setText(QApplication::translate("LightEdit", "21", nullptr));
        label_28->setText(QApplication::translate("LightEdit", "22", nullptr));
        label_29->setText(QApplication::translate("LightEdit", "23", nullptr));
        label_30->setText(QApplication::translate("LightEdit", "24", nullptr));
        label_31->setText(QApplication::translate("LightEdit", "7", nullptr));
        label_32->setText(QApplication::translate("LightEdit", "8", nullptr));
        label_33->setText(QApplication::translate("LightEdit", "9", nullptr));
        label_34->setText(QApplication::translate("LightEdit", "10", nullptr));
        label_35->setText(QApplication::translate("LightEdit", "11", nullptr));
        label_36->setText(QApplication::translate("LightEdit", "12", nullptr));
        label_37->setText(QApplication::translate("LightEdit", "13", nullptr));
        label_38->setText(QApplication::translate("LightEdit", "14", nullptr));
        label_39->setText(QApplication::translate("LightEdit", "15", nullptr));
        label_40->setText(QApplication::translate("LightEdit", "16", nullptr));
        label_41->setText(QApplication::translate("LightEdit", "17", nullptr));
        label_42->setText(QApplication::translate("LightEdit", "18", nullptr));
        label_43->setText(QApplication::translate("LightEdit", "19", nullptr));
        label_44->setText(QApplication::translate("LightEdit", "20", nullptr));
        label_45->setText(QApplication::translate("LightEdit", "21", nullptr));
        label_46->setText(QApplication::translate("LightEdit", "22", nullptr));
        label_47->setText(QApplication::translate("LightEdit", "23", nullptr));
        label_48->setText(QApplication::translate("LightEdit", "24", nullptr));
        pushButton->setText(QApplication::translate("LightEdit", "\347\241\256\350\256\244", nullptr));
    } // retranslateUi

};

namespace Ui {
    class LightEdit: public Ui_LightEdit {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LIGHTEDIT_H
